version: "3.7"
services:

  app:
    image: laravel-app:latest
    container_name: FOOBAR_laravel
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    labels:
      - "traefik.enable=true"
    volumes:
      - ./src:/var/www
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: FOOBAR_nginx
    restart: unless-stopped
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.FOOBAR.rule=Host(`FOOBAR.bar.fr`)"
      - "traefik.http.routers.FOOBAR.entrypoints=websecure"
      - "traefik.http.routers.FOOBAR.tls.certresolver=myhttpchallenge"
      - traefik.docker.network=web

      - "traefik.http.routers.FOOBAR-http.rule=Host(`FOOBAR.bar.fr`)"
      - "traefik.http.routers.FOOBAR-http.entrypoints=web"

      - traefik.http.routers.FOOBAR-http.middlewares=FOOBAR-redirect
      - traefik.http.middlewares.FOOBAR-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.FOOBAR-redirect.redirectscheme.permanent=true
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    networks:
      - internal
      - web
    depends_on :
      - app

  db:
    image: mariadb:latest
    container_name: FOOBAR_db
    volumes:
      - ./mariadb/data:/var/lib/mysql
    depends_on:
      - nginx
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
    environment:
      MARIADB_DATABASE: FOOBAR
      MARIADB_ROOT_PASSWORD: "MyPassW0rd!23"
    networks:
      - internal

  queue:
    image: laravel-app:latest
    container_name: FOOBAR_queue
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./src:/var/www
    networks:
      - internal
    labels:
      - "traefik.enable=true"
    command: ["/usr/local/bin/laravel-queue"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: FOOBAR_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.FOOBAR-phpmyadmin.rule=Host(`FOOBAR-phpmyadmin.bar.fr`)"
      - "traefik.http.routers.FOOBAR-phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.FOOBAR-phpmyadmin.tls.certresolver=myhttpchallenge"
      - traefik.docker.network=web
      - "traefik.http.routers.FOOBAR-http-phpmyadmin.rule=Host(`FOOBAR-phpmyadmin.bar.fr`)"
      - "traefik.http.routers.FOOBAR-http-phpmyadmin.entrypoints=web"
      - traefik.http.routers.FOOBAR-http-phpmyadmin.middlewares=FOOBAR-redirect-phpmyadmin
      - traefik.http.middlewares.FOOBAR-redirect-phpmyadmin.redirectscheme.scheme=https
      - traefik.http.middlewares.FOOBAR-redirect-phpmyadmin.redirectscheme.permanent=true
    networks:
      - internal
      - web


networks:
  internal:
  web:
    external: true
